### ISSUE TITLE
.coveralls.yml - for your own good :)

### ISSUE THREAD

**Issue by Alorel** [LAJW/fugazi#1] opened 2016-05-14 20:34 UTC
[Remove your repo token from the public repo](https://coveralls.zendesk.com/hc/en-us/articles/201347419-Coveralls-currently-supports)

> The option repo_token (found on your repository's page on Coveralls) is used to specify which project on Coveralls your project maps to. This is only needed for private repos and should be kept secret -- anyone could use it to submit coverage data on your repo's behalf.

**Comment by LAJW** [comment] 2016-05-14 20:49
Thanks I know. The problem is that I am unable to make travis send the report to coveralls (I'm updating this manually every release). If you have some experience with this, I'd love some help.

**Comment by LAJW** [comment] 2016-05-14 21:11
Finally figured it out.
`travis.yml` had to have `- script = "npm run coverage"` so as to generate the coverage report. I believed too much in travis ;)
Closing!

**Closed as completed by LAJW** 2016-05-14 21:11 UTC
